# Étape 1 : image de base avec Java
FROM openjdk:21-jdk-slim

# Étape 2 : répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : copier le JAR dans le conteneur
COPY target/gatewayMicroservice-0.0.1-SNAPSHOT.jar app.jar

# Étape 4 : exposer le port que ton service utilise
EXPOSE 8080

# Étape 5 : commande pour lancer l'app
ENTRYPOINT ["java", "-jar", "app.jar"]